version: '3.8'
services:
  database:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./dolfin_server
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://database:27017/
      - API_KEY = ZGJmYmY0MjUtNjE3MS00MWVjLWEyMmItMzBhYTliMmQ4OGQyOjhlOTYwNTM0LTI1OGItNGUzMC1hOWViLWY2OGM0MjdlMjg0ZA==
    depends_on:
      - database
  frontend:
    build:
      context: ./dolfin_web
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge